### PR TITLE
Added korean documents

### PR DESCRIPTION
**Pull request by tasoo-oos**
- Korean README.md
- Korean HELP.md
- Edited vite.config.ts slightly to make korean description more natural

Also,
- Edited support site list in README.md and README_CN.md according to vite.config.ts's match list
- A few typo fix

### CODE REVIEW

**Comment by tasoo-oos** [comment]
I just found I18n localization utility.
I will try to impliment korean there, too.

**Comment by MapoMagpie** [comment]
This is great!

**Comment by tasoo-oos** [comment]
Added
- Full korean i18n localization
- A little tweak on getting I18nIndex logic (to function)
- Added one line on README (CN is done with GPT, so please see if it did right.)

**Comment by tasoo-oos** [comment]
Also, would you raise version number, so updated version is uploaded to other sites?

**Pull request merged**
